spring:
  cloud:
    bus:
      enabled: true
    config:
      uri:
        - http://localhost:8888
      profile: dev
    profiles:
      active: dev
  application:
    name: trip-planner-model-service
logging:
  level:
    root: info
server:
  port: 8082
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    lease:
      duration: 5
#ribbon:
#  eureka:
#    enabled: true
trip:
  username: user
  password: user
# first solution is pass username and password here

